server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:prography
    username: sa
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  h2:
    console:
      enabled: true
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 2000
        one-indexed-parameters: on
springdoc:
  packages-to-scan: com.example.prography_quest
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api
    groups:
      enabled: true
  cache:
    disabled: true
  swagger-ui:
    path: /ui
    operations-sorter: method

  jwt:
    refresh:
      secret: 7b190110066d09a1f88c5970fa55d5c2a61e52a2e4b984c7704966ab6bebad9791b5984136695239a67d98027ebcea2f36ba00ce628c662d7e0d43b5066d6567
    access:
      secret: 8937d7116cd6b9f184586f367e596d44661d838421db2fc23f7be1355df04d50838c9fbec843ef67cfe5856da75559ff69e48c3e6e00652f448fb975cc1c46d4