# github action yml 을 작성하는 법
# dockerfile image 생성 , 작동하는 법
# 라즈베리파이 연동 서버

name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'openjdk'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run : chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker & Push
        run : |
            docker login -v ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build -t ${{ secrets.DOCKER_REPO }}/  
            docker push ${{ secrets.DOCKER_REPO }}/
